# Generated by Django 5.1.5 on 2025-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_userprofile_delete_assignrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(default='No Selected', max_length=255),
        ),
    ]
