# Generated by Django 5.1.5 on 2025-03-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentprofile_level_userprofile_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Classrooms',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
