# Generated by Django 5.1.5 on 2025-03-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_teacherprofile_user_delete_classrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(default='', upload_to='teacher_avatars/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile_teacher_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institute',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.DeleteModel(
            name='DailyMissions',
        ),
    ]
