# Generated by Django 5.1.5 on 2025-03-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentcalendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_reached', models.IntegerField()),
                ('level_achievement', models.CharField(max_length=255)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='student.studentprofile')),
            ],
        ),
    ]
