# Generated by Django 5.1.5 on 2025-03-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_levelhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unlocked', 'Unlocked'), ('all', 'All'), ('coming_soon', 'Coming Soon')], default='coming_soon', max_length=20)),
                ('unlocked_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_milestones', to='student.studentprofile')),
            ],
        ),
    ]
