# Generated by Django 5.1.5 on 2025-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_levelmilestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('rewards', models.TextField()),
                ('points', models.PositiveIntegerField()),
            ],
        ),
    ]
