# Generated by Django 5.1.5 on 2025-03-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_levelrewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('unlocked', 'Unlocked'), ('in_progress', 'In Progress'), ('locked', 'Locked')], default='locked', max_length=20)),
                ('description', models.TextField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='student.studentprofile')),
            ],
        ),
    ]
