# Generated by Django 5.1.5 on 2025-03-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentloginstreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('test_type', models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], max_length=10)),
                ('obtained_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_history', to='student.studentprofile')),
            ],
        ),
    ]
