# Generated by Django 5.1.5 on 2025-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studenttesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
