# Generated by Django 5.1.5 on 2025-04-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentprofile_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecentActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='student.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
