# Generated by Django 5.1.5 on 2025-04-09 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_studentrecentactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymissions',
            name='date_assigned',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='dailymissions',
            unique_together={('student', 'mission_name', 'date_assigned')},
        ),
    ]
