# Generated by Django 5.1.5 on 2025-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='students',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
