# Generated by Django 5.1.5 on 2025-03-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
