# Generated by Django 5.1.5 on 2025-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_classrooms_students_delete_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='institute',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
