# Generated by Django 5.1.5 on 2025-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_classrooms_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='classroom_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
