# Generated by Django 5.1.5 on 2025-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherprofile_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='name',
        ),
    ]
