# Generated by Django 5.1.5 on 2025-03-26 15:39

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_classrooms_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='classroom_code',
            field=models.CharField(default=teacher.models.generateUniqueCode, max_length=6, unique=True),
        ),
    ]
