# Generated by Django 5.1.5 on 2025-03-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_classrooms_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='students_id',
            field=models.JSONField(default=list),
        ),
    ]
