# Generated by Django 5.1.5 on 2025-03-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_classrooms_students_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
