# Generated by Django 5.1.5 on 2025-03-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_classroomsharedmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomsTestActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_activities', to='teacher.classrooms')),
            ],
        ),
    ]
