# Generated by Django 5.1.5 on 2025-03-28 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_classroomcalendarevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomstestactivities',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroomstestactivities',
            name='pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomstestactivities',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroomstestactivities',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherAIPodcastManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='teacher.classrooms')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='teacher.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRecentActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='teacher.teacherprofile')),
            ],
        ),
    ]
