# Generated by Django 5.1.5 on 2025-03-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_classroomstestactivities_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTestStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_store', to='teacher.classroomstestactivities')),
            ],
        ),
    ]
