# Generated by Django 5.1.5 on 2025-04-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_classteststore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='students_id',
            new_name='students_username',
        ),
    ]
